Feature/2022 mo 313 1
aiit2022-pbl-okuhara/play-security pull request #18
Opened 2022-08-03 15:08 UTC by Masaru-Yamada

## Backlog Issue
https://aiit-isa.backlog.jp/view/2022MO-313

## 対応した内容
- シナリオ一覧の作成
- テストコードは未実装

## 期待される結果
- テストコードを書いて再度pull requestを送る

2022-08-05 10:31 UTC, mi-bear requested changes

2022-08-05 10:31 UTC, mi-bear commented on actions/scenarios.go
> +	tx, ok := c.Value("tx").(*pop.Connection)
tx.Value の受け取りは tx だけで良かったと思います。毎回 tx connection チェックはしなくてもいいかも。

2022-08-05 10:31 UTC, mi-bear commented on actions/scenarios.go
> +		return err
```
return errors.WithStack(err)
```

他の処理と同じく、上記がいいです。

2022-08-05 10:31 UTC, mi-bear commented on actions/scenarios.go
> +	q.Where(`stories.organization_id = ?`, u.OrganizationID)
story、scenario、role を同時に取得できると思います。
https://blog.gobuffalo.io/associations-with-pop-1-to-n-2fb3e1c3833f
ここ、参考にしてみてください。

2022-08-05 10:31 UTC, mi-bear commented on actions/scenarios.go
> +	u := c.Data()["current_user"].(*models.User)
この取得方法がホントにいいのか、ちょっとわからない... (間違ってはいないです！) 
一旦ここはこれで OK だと思います〜

2022-08-05 10:35 UTC, mi-bear commented on actions/scenarios.go
> +	q.Where(`stories.organization_id = ?`, u.OrganizationID)
あわせて、ユーザが持つデータ (Play 回数など) は、別で取得して key を scenario にすると良いのかもしれない、と思いました。

2022-08-06 12:58 UTC, mi-bear commented on actions/scenarios.go
> +		q = tx.Q()
このあたり、 n+1 問題かも。

2022-08-07 11:53 UTC, closed without merging

2022-08-08 08:09 UTC, Masaru-Yamada commented on actions/scenarios.go
> +	q.Where(`stories.organization_id = ?`, u.OrganizationID)
story、scenarioまではとれるのですが、scenarioの中にあるroleとhistoryが取得できていないようです.....
ひとまず、roleとhistoryは別で取得する方向で実装してみます